// frontend/src/components/SlideOver/SlideOver.vue
<template>
  <transition
    enter-active-class="transform transition ease-in-out duration-500 sm:duration-700"
    enter-class="translate-x-full"
    enter-to-class="translate-x-0"
    leave-active-class="transform transition ease-in-out duration-500 sm:duration-700"
    leave-class="translate-x-0"
    leave-to-class="translate-x-full"
  >
    <div
      v-if="areFiltersVisibile"
      class="slide-over"
    >
      <section class="slide-over__container">
        <div class="w-screen max-w-md">
          <div class="h-full divide-y divide-gray-200 flex flex-col bg-white shadow-xl">
            <div class="h-0 flex-1 py-6 space-y-6 overflow-y-scroll">
              <header class="px-4 sm:px-6">
                <div class="flex items-start justify-evenly space-x-3">
                  <h2 class="text-lg leading-7 font-medium text-gray-900 text-center">
                    Allergies
                  </h2>
                  <div class="h-7 flex items-center">
                    <BaseButton
                      aria-label="Close panel"
                      class="text-gray-400 hover:text-gray-500
                      transition ease-in-out duration-150"
                      @click="closeSlideOver"
                    >
                      <svg
                        class="h-6 w-6"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M6 18L18 6M6 6l12 12"
                        />
                      </svg>
                    </BaseButton>
                  </div>
                </div>
              </header>
              <div class="relative flex-1 px-4 sm:px-6 max-w-10 my-0 mx-auto">
                <BaseWrapper :column="1">
                  <span
                    v-for="(allergy, index) in allergies"
                    :key="index"
                    class="flex justify-between border border-cool-gray-300 px-2 py-1 items-center rounded-lg cursor-pointer shadow-lg"
                    @click="toggleFilter(index)"
                  >
                    <BaseIcon :name="allergy.label"/>
                    {{ allergy.label }}
                    <BaseToggle :is-on="allergy.isOn" />
                  </span>
                </BaseWrapper>
              </div>
              <div class="flex-shrink-0 px-4 py-4 space-x-4 flex justify-end">
                <span class="inline-flex rounded-md shadow-sm">
                  <BaseButton
                    type="BaseButton"
                    class="py-2 px-4 border border-gray-300 rounded-md
                  text-sm leading-5 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:border-blue-300
                  focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800 transition duration-150 ease-in-out"
                  >
                    Cancel
                  </BaseButton>
                </span>
                <span class="inline-flex rounded-md shadow-sm">
                  <BaseButton
                    type="submit"
                    class="inline-flex justify-center py-2 px-4 border border-transparent
                      text-sm leading-5 font-medium rounded-md text-white bg-red-600 hover:bg-red-500 focus:outline-none
                    focus:border-indigo-700 focus:shadow-outline-red active:bg-red-700 transition duration-150 ease-in-out"
                  >
                    Save
                  </BaseButton>
                </span>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </transition>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import BaseButton from '@/components/BaseButton/BaseButton.vue';
import BaseToggle from '@/components/BaseToggle/BaseToggle.vue';
import BaseWrapper from '@/components/BaseWrapper/BaseWrapper.vue';
import BaseIcon from '~/BaseIcon/BaseIcon.vue';

export default defineComponent({
  name: 'SlideOver',
  props: {
    areFiltersVisibile: {
      type: Boolean,
      required: false,
      default: false,
    },
  },
  components: {
    BaseButton,
    BaseToggle,
    BaseWrapper,
    BaseIcon,
  },
  data() {
    return {
      isOn: false,
      allergies: [
        {
          label: 'soy',
          isOn: false,
        },
        {
          label: 'meat',
          isOn: false,
        },
        {
          label: 'gluten',
          isOn: false,
        },
        {
          label: 'nuts',
          isOn: false,
        },
        {
          label: 'dairy',
          isOn: false,
        },
        {
          label: 'shellfish',
          isOn: false,
        },
      ],
    };
  },
  methods: {
    closeSlideOver(): void {
      this.$emit('close-side-over', false);
    },

    toggleFilter(index: number): void {
      this.allergies[index].isOn = !this.allergies[index].isOn;
    },
  },
});

</script>

<style scoped>
.slide-over {
  @apply inset-0 overflow-hidden absolute;
}

</style>

// app/src/components/SlideOver/SlideOver.tsx
import React, { FC, SetStateAction } from "react";
import { Transition } from "@headlessui/react";

interface Props {
  isSlideOverOpen: boolean;
  setIsSlideOverOpen: (value: SetStateAction<boolean>) => void;
}

const SlideOver: FC<Props> = ({ isSlideOverOpen, setIsSlideOverOpen }) => {
  if (isSlideOverOpen) {
    return (
      <section
        className="fixed inset-0 overflow-hidden"
        aria-labelledby="slide-over-title"
        role="dialog"
        aria-modal="true"
      >
        <div className="absolute inset-0 overflow-hidden">
          {isSlideOverOpen && (
            <div className="absolute inset-0" aria-hidden="true"></div>
          )}
          {isSlideOverOpen && (
            <Transition
              show={isSlideOverOpen}
              enter="transform transition ease-in-out duration-500 sm:duration-700"
              enterFrom="translate-x-full"
              enterTo="translate-x-0"
              leave="transform transition ease-in-out duration-500 sm:duration-700"
              leaveFrom="translate-x-0"
              leaveTo="translate-x-full"
            >
              <div className="absolute inset-y-0 right-0 pl-10 max-w-full flex">
                <div className="w-screen max-w-md">
                  <div className="h-full divide-y divide-gray-200 flex flex-col bg-white shadow-xl">
                    <div className="min-h-0 flex-1 flex flex-col py-6 overflow-y-scroll">
                      <div className="px-4 sm:px-6">
                        <div className="flex items-start justify-between">
                          <h2
                            className="text-lg font-medium text-gray-900"
                            id="slide-over-title"
                          >
                            Panel title
                          </h2>
                          <div className="ml-3 h-7 flex items-center">
                            <button
                              onClick={() => setIsSlideOverOpen(false)}
                              className="bg-white rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                            >
                              <span className="sr-only">Close panel</span>
                              <svg
                                className="h-6 w-6"
                                xmlns="http://www.w3.org/2000/svg"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                                aria-hidden="true"
                              >
                                <path
                                  stroke-linecap="round"
                                  stroke-linejoin="round"
                                  stroke-width="2"
                                  d="M6 18L18 6M6 6l12 12"
                                />
                              </svg>
                            </button>
                          </div>
                        </div>
                      </div>
                      <div className="mt-6 relative flex-1 px-4 sm:px-6">
                        <div
                          className="h-full border-2 border-dashed border-gray-200"
                          aria-hidden="true"
                        ></div>
                      </div>
                    </div>
                    <div className="flex-shrink-0 px-4 py-4 flex justify-end">
                      <button
                        onClick={() => setIsSlideOverOpen(false)}
                        className="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                      >
                        Cancel
                      </button>
                      <button
                        onClick={() => setIsSlideOverOpen(false)}
                        className="ml-4 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                      >
                        Save
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </Transition>
          )}
        </div>
      </section>
    );
  }
  return null;
};

export { SlideOver };
